language: php

php:
  - 7.1
  - 7.3
  - 7.4
  - 8.0

before_install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

before_script:
  - cp .env.example .env

script:
  - ./vendor/bin/phpunit --verbose tests/SerializeTest
  - ./vendor/bin/phpunit --verbose tests/MapperTest

jobs:
  include:
    - php: 7.3
      env: TYPE=phpstan
      script:
        - ./vendor/bin/phpstan analyse
    - php: 7.4
      env: TYPE=phpstan
      script:
        - ./vendor/bin/phpstan analyse
    - php: 8.0
      env: TYPE=phpstan
      script:
        - ./vendor/bin/phpstan analyse
